# Generated by Django 5.1.1 on 2024-11-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.TextField()),
                ("first_name", models.TextField()),
                ("street_num", models.IntegerField()),
                ("street_name", models.TextField()),
                ("apt_num", models.IntegerField()),
                ("zipcode", models.IntegerField(max_length=5)),
                ("dob", models.DateField()),
                ("reg_date", models.DateField()),
                ("affiliation", models.CharField(max_length=2)),
                ("precint", models.IntegerField()),
                ("state_20", models.BooleanField()),
                ("town_21", models.BooleanField()),
                ("primary_21", models.BooleanField()),
                ("general_22", models.BooleanField()),
                ("town_23", models.BooleanField()),
            ],
        ),
    ]
