# Generated by Django 5.1.1 on 2024-11-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0003_voter_score_alter_voter_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voter",
            name="affiliation",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="apt_num",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="general_22",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="precint",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="primary_21",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="reg_date",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="score",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="state_20",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="street_name",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="street_num",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="town_21",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="town_23",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="zipcode",
        ),
        migrations.AddField(
            model_name="voter",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="date_of_registration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="party_affiliation",
            field=models.CharField(default="Unaffiliated", max_length=50),
        ),
        migrations.AddField(
            model_name="voter",
            name="precinct_number",
            field=models.CharField(default="0000", max_length=10),
        ),
        migrations.AddField(
            model_name="voter",
            name="residential_apartment_number",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="residential_street_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="voter",
            name="residential_street_number",
            field=models.CharField(default="0", max_length=10),
        ),
        migrations.AddField(
            model_name="voter",
            name="residential_zip_code",
            field=models.CharField(default="00000", max_length=10),
        ),
        migrations.AddField(
            model_name="voter",
            name="v20state",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="voter",
            name="v21primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="voter",
            name="v21town",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="voter",
            name="v22general",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="voter",
            name="v23town",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="first_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="voter",
            name="last_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
