# Generated by Django 5.1.1 on 2024-11-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voter_analytics",
            "0004_remove_voter_affiliation_remove_voter_apt_num_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="first_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="last_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="party_affiliation",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="precinct_number",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="residential_apartment_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="residential_street_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="residential_street_number",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="residential_zip_code",
            field=models.TextField(),
        ),
    ]
