# Generated by Django 5.1.1 on 2024-11-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voter_analytics",
            "0005_alter_voter_first_name_alter_voter_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="voter_score",
            field=models.IntegerField(default=0),
        ),
    ]
