# Generated by Django 5.1.3 on 2024-11-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_rename_dragon_dragons"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Dragons",
            new_name="Dragon",
        ),
    ]
