# Generated by Django 5.1.3 on 2024-12-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_alter_profile_user_friend"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friend",
            old_name="added_on",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="friend",
            name="friend",
        ),
        migrations.RemoveField(
            model_name="friend",
            name="user",
        ),
        migrations.AddField(
            model_name="friend",
            name="profile1",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile1",
                to="project.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friend",
            name="profile2",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile2",
                to="project.profile",
            ),
            preserve_default=False,
        ),
    ]
