# Generated by Django 5.1.3 on 2024-12-10 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_favoritedragon_delete_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="availability",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="yes", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="favoritedragon",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_dragon",
                to="project.profile",
            ),
        ),
    ]
