# Generated by Django 5.1.3 on 2024-12-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_wishlist_availability_alter_favoritedragon_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="availability",
        ),
        migrations.AddField(
            model_name="wishlist",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
