# Generated by Django 5.1.3 on 2024-12-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_remove_wishlist_availability_wishlist_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="available",
        ),
        migrations.AddField(
            model_name="dragon",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
