# Generated by Django 5.1.3 on 2024-12-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_remove_wishlist_available_dragon_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="dragon",
            name="wiki_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
